version: "3.9"

networks:
  bridge:

services:
  ### Nextjs App ################################################
  app:
    container_name: ${APP_NAME}-app
    image: ${APP_NAME}
    restart: always
    ports:
      - ${APP_PORT}:3000
    build: ./
    volumes:
      - ${APP_CODE_PATH_HOST}:/usr/src/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    networks:
      - bridge

  ### MySQL ################################################
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - bridge

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  ### NGINX Server #########################################
  nginx:
    container_name: ${APP_NAME}-nginx
    image: ${APP_NAME}-nginx
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - bridge
